prompt: 
  pattern: '{time}~{username}@ {branch} {pwd} '
  username: [white, bold]
  host:     green
  time:     blue
  branch:   red
  repo:     white
  pwd:      white


settings:
  label: 'sofia'
  tab_width: 42
  max_completion_tab_height: 12
  bash_literal: '%'

style:
  token_fun: blue
  token_method: blue
  token_path: red
  token_arg: green
  token_int: blue
  token_string: cyan
  token_block: white
  error: orange
  font: default
  size: default
  result: orange
  background: black

  